### ISSUE TITLE
IllegalAccessError: tried to access field com.relevantcodes.extentreports.model.SystemProperties.info from class com.relevantcodes.extentreports.SystemInfo

### ISSUE THREAD

**Issue by ilitkevich** [anshooarora/extentreports#101]
Hi Anshoo!

For some reason I start getting next error (for all 2.x versions) yesterday as soon as I start playing with v2.10:
```
[TestRunner] Running the tests in 'DevSuiteTests' with parallel mode:false
[RunInfo] Adding method selector: org.testng.internal.XmlMethodSelector@d041cf priority: 10
org.testng.TestNGException: 
An error occurred while instantiating class MedeTests.Login.LoginTests: tried to access field com.relevantcodes.extentreports.model.SystemProperties.info from class com.relevantcodes.extentreports.SystemInfo
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:394)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:295)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:118)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:183)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:128)
	at org.testng.TestRunner.initMethods(TestRunner.java:416)
	at org.testng.TestRunner.init(TestRunner.java:242)
	at org.testng.TestRunner.init(TestRunner.java:212)
	at org.testng.TestRunner.<init>(TestRunner.java:166)
	at org.testng.remote.RemoteTestNG$1.newTestRunner(RemoteTestNG.java:143)
	at org.testng.remote.RemoteTestNG$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG.java:272)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:587)
	at org.testng.SuiteRunner.init(SuiteRunner.java:161)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1266)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1253)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1107)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalAccessError: tried to access field com.relevantcodes.extentreports.model.SystemProperties.info from class com.relevantcodes.extentreports.SystemInfo
	at com.relevantcodes.extentreports.SystemInfo.setInfo(SystemInfo.java:46)
	at com.relevantcodes.extentreports.SystemInfo.<init>(SystemInfo.java:57)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:47)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:100)
	at Automation.Utils.ExtentManager.getInstance(ExtentManager.java:14)
	at Automation.Utils.TestBase.<clinit>(TestBase.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:382)
	... 26 more

Process finished with exit code 0
```

**ExtentManager:**
```
public class ExtentManager {
    private static ExtentReports extent;

    public static ExtentReports getInstance() {

        if (extent == null) {
            extent = new ExtentReports("./ExtentReport.html", true); // <- at Automation.Utils.ExtentManager.getInstance(ExtentManager.java:14)
            extent.config()
                    .documentTitle("Automation Report")
                    .reportName("Regression")
                    .reportHeadline("")
                    .insertCustomStyles(".test { border: 1px solid lightseagreen; }")
                    .insertJs("$('.test.warning').each(function() { $(this).addClass('pass').removeClass('warning'); }); $('.test-status.warning').each(function() { $(this).addClass('pass').removeClass('warning').text('pass'); });$('.tests-quick-view .status.warning').each(function() { $(this).addClass('pass').removeClass('warning').text('PASS'); }); testSetChart(); ");
            extent
                    .addSystemInfo("Selenium Version", "2.46")
                    .addSystemInfo("Environment", "C60 Production");

        }
        return extent;
    }
}
```
**at Automation.Utils.TestBase.<clinit>(TestBase.java:41)**
```    public static ExtentReports extent = ExtentManager.getInstance(); ```

I rolled back to v2.05 but no luck, still getting the same Exception. SystemInfo.java gives me 404: https://github.com/anshooarora/extentreports/blob/master/java/2.x/src/com/relevantcodes/extentreports/SystemInfo.java

Thank you.

**Comment by ilitkevich** [comment]
On another workstation, where I did not swing between 2.05 -> 2.10 -> 2.05, everything works fine. I guess that's because Maven didn't update local repository and SystemInfo.java exists there.

**Comment by ilitkevich** [comment]
With v.2.10 tests actually started and failed on AfterMethod:
````
...
... TestNG 6.9.6 by CÃ©dric Beust (cedric@beust.com)
...

[TestRunner] Running the tests in 'DevSuiteTests' with parallel mode:false
[RunInfo] Adding method selector: org.testng.internal.XmlMethodSelector@48140564 priority: 10
[TestClass] Creating TestClass for [ClassImpl class=MedeTests.Login.LoginTests]
[TestNG] Running:
  C:\DEVSVN\xxxxx\src\main\resources\XMLSuits\_DEV.xml

[SuiteRunner] Created 1 TestRunners
[TestRunner] Running test DevSuiteTests on 1  classes,  included groups:[] excluded groups:[]
===== Test class
MedeTests.Login.LoginTests
  @BeforeClass TestBase.beforeClass(java.lang.String, java.lang.String)[pri:0, instance:MedeTests.Login.LoginTests@6acdbdf5]
    @Test LoginTests.FailedBlankLogin()[pri:0, instance:MedeTests.Login.LoginTests@6acdbdf5]
    @Test LoginTests.FailedIncorrectLogin()[pri:0, instance:MedeTests.Login.LoginTests@6acdbdf5]
    @Test LoginTests.SuccessfulLogin(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:MedeTests.Login.LoginTests@6acdbdf5]
  @AfterMethod TestBase.catchExceptions(org.testng.ITestResult, org.testng.ITestContext)[pri:0, instance:MedeTests.Login.LoginTests@6acdbdf5]
  @AfterClass TestBase.afterClass()[pri:0, instance:MedeTests.Login.LoginTests@6acdbdf5]
======
[Invoker 561247961] Invoking @BeforeClass TestBase.beforeClass(java.lang.String, java.lang.String)[pri:0, instance:MedeTests.Login.LoginTests@6acdbdf5]
```

With v.2.10 I`m getting next Exception:

```
java.lang.NoClassDefFoundError: org/jsoup/nodes/Node
	at com.relevantcodes.extentreports.HTMLReporter.addTest(HTMLReporter.java:267)
	at com.relevantcodes.extentreports.Report.addTest(Report.java:70)
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:171)
	at Automation.Utils.TestBase.catchExceptions(TestBase.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:708)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.jsoup.nodes.Node
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
java.lang.NoClassDefFoundError: org/jsoup/nodes/Node
	at com.relevantcodes.extentreports.HTMLReporter.addTest(HTMLReporter.java:267)
	at com.relevantcodes.extentreports.Report.addTest(Report.java:70)
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:171)
	at Automation.Utils.TestBase.catchExceptions(TestBase.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:708)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.jsoup.nodes.Node
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
java.lang.NoClassDefFoundError: org/jsoup/nodes/Node
	at com.relevantcodes.extentreports.HTMLReporter.addTest(HTMLReporter.java:267)
	at com.relevantcodes.extentreports.Report.addTest(Report.java:70)
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:171)
	at Automation.Utils.TestBase.catchExceptions(TestBase.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:708)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.jsoup.nodes.Node
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
```
**at Automation.Utils.TestBase.catchExceptions(TestBase.java:115)**
```
extent.endTest(test);
```

**Comment by anshooarora** [comment]
I am unable to reproduce this.  Can you do a clean maven install/copy-dependencies and try again?  Do you also have jsoup and xerial-sqlite in your build path?

**Comment by ilitkevich** [comment]
jsoup and xerial-sqlite are in build path: 
![2015-10-16_15-43-27](https://cloud.githubusercontent.com/assets/15159015/10551695/6d028bc4-741c-11e5-8212-500edb18556b.png)

I localized problem, it`s **extent.endTest(test);** from @AfterMethod.

```
    public static WebDriver driver;
    public static ExtentTest test;
    public static ExtentReports extent = ExtentManager.getInstance();

    @AfterMethod(alwaysRun=true)
    public void catchExceptions(final ITestResult testResult, final ITestContext testContext){
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat formatDateTime = new SimpleDateFormat("dd_MM_yyyy_hh_mm_ss");
        SimpleDateFormat formatDate = new SimpleDateFormat("dd_MM_yyyy");
        String methodName = testResult.getName();
        String testName = testContext.getName();
        if(testResult.getStatus() == ITestResult.FAILURE){
            File scrFile = getScreenShotAsFile();
            try {
                copyFile(scrFile, new File("./target/"+ formatDate.format(calendar.getTime()) + "/" + testName + "/" + methodName + "_" + formatDateTime.format(calendar.getTime()) + ".png"));
                Path source = Paths.get(String.valueOf(scrFile));
                Path destination = Paths.get("./target/"+ formatDate.format(calendar.getTime()) + "/" + testName + "/" + methodName + "_" + formatDateTime.format(calendar.getTime()) + ".png");
                Files.deleteIfExists(destination);
                Files.copy(source, destination);
                test.log(LogStatus.INFO, "Error Snapshot: " + test.addScreenCapture(destination.toString()));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        if(testResult.getStatus() == ITestResult.SKIP){
            test.log(LogStatus.SKIP,"This test was skipped");
        }
        extent.endTest(test);
        extent.flush();
    }
```

Without **extent.endTest(test);** tests are running well but the report is empty. This structure served me well since ExtentReport v2.0 and I have no clue what could happened.

**Comment by anshooarora** [comment]
Is this issue on all your machines?  You said on a different machine it is working fine.

<code>endTest</code> is what builds and finalizes the model without which the view will remain empty.

It still seems like a build issue to me because the issue is the package not being able to find the jsoup class:  <code>java.lang.NoClassDefFoundError: org/jsoup/nodes/Node</code>.

Can you do a clean / build and try again?

**Comment by ilitkevich** [comment]
You're right, it's clearly my workstation problem. On my coworker's 2.10 works just fine. Great design, BTW.

Thanks for you help!

**Comment by ilitkevich** [comment]
Updated JDK/JRE to the latest versions.
