### ISSUE TITLE
Issue with latest version 2.10, 2.11 beta.. with extent.flush()

### ISSUE THREAD

**Issue by GurudathRao** [anshooarora/extentreports#104]
extent.flush() fails with fallowing trace...so report generation fails. Can you please check this.

2015-10-19 16:17:34,083 ERROR [SoapUI] An error occurred [org.jsoup.parser.Parser.unescapeEntities(Ljava/lang/String;Z)Ljava/lang/String;], see error log for details
2015-10-19 16:17:34,083 ERROR [errorlog] java.lang.NoSuchMethodError: org.jsoup.parser.Parser.unescapeEntities(Ljava/lang/String;Z)Ljava/lang/String;
java.lang.NoSuchMethodError: org.jsoup.parser.Parser.unescapeEntities(Ljava/lang/String;Z)Ljava/lang/String;
at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:179)
at com.relevantcodes.extentreports.Report.flush(Report.java:97)
at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:223)
at com.relevantcodes.extentreports.ExtentReports$flush$2.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)

**Comment by anshooarora** [comment]
This is not an issue with Extent, and since you are using Groovy, I am unable to debug.

A quick search gave me the following results:

http://stackoverflow.com/questions/10326343/exception-java-lang-nosuchmethoderror-org-objectweb-asm-classwriter-on-viewin
http://stackoverflow.com/questions/9223689/solve-error-java-lang-nosuchmethoderror-org-codehaus-groovy-ast-modulenode-gets

**Comment by anshooarora** [comment]
Can you try once with the latest beta:  <a href='http://relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.11.0-beta-2.zip'>2.11.0-beta-2</a>?

**Comment by GurudathRao** [comment]
Still the same issues :(

java.lang.NoSuchMethodError: org.jsoup.parser.Parser.unescapeEntities(Ljava/lang/String;Z)Ljava/lang/String; error at line: 76

Trace as below..
2015-10-26 14:53:25,192 ERROR [errorlog] java.lang.NoSuchMethodError: org.jsoup.parser.Parser.unescapeEntities(Ljava/lang/String;Z)Ljava/lang/String;
java.lang.NoSuchMethodError: org.jsoup.parser.Parser.unescapeEntities(Ljava/lang/String;Z)Ljava/lang/String;
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:207)
	at com.relevantcodes.extentreports.Report.flush(Report.java:89)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:216)
	at com.relevantcodes.extentreports.ExtentReports$flush$2.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
	at Script1.run(Script1.groovy:76)
	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:92)
	at com.eviware.soapui.support.scripting.groovy.SoapUIProGroovyScriptEngineFactory$SoapUIProGroovyScriptEngine.run(SoapUIProGroovyScriptEngineFactory.java:76)
	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:155)
	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:263)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by GurudathRao** [comment]
Hi Anshoo,

Sorted the problem :). SoapUI by default has a jsoup jar in its libraries folder having version 1.6.1. This was causing the conflict. Rather was taking precedence. I have replaced it with Jsoup 1.8.3.
Works perfectly! 
Thanks again. Closing the issue.

**Comment by GurudathRao** [comment]
Just to add I have tested this in the stable version 2.10 and its working fine.
