### ISSUE TITLE
FreeMarker template error in version 2.40.0

### ISSUE THREAD

**Issue by subratkumarmandal** [anshooarora/extentreports#190]
I am facing below exception while calling flush report file is generated without any report it's a blank file.
FreeMarker template error:
The following has evaluated to null or missing:
==> log.stepName  [in template "Extent.ftl" at line 309, column 93]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${log.stepName}  [in template "Extent.ftl" at line 309, column 91]

**Comment by anshooarora** [comment]
Please provide the steps to reproduce.

Are you using stepName for the 1st step and nothing for subsequent?

**Comment by subratkumarmandal** [comment]
In my case not all the tests are having step name in some scenarios it's stepname and details and in soem cases it's only details. this approach worked in previous version like 2.10.0

**Comment by anshooarora** [comment]
If you use stepName for the 1st log, the same process should ideally be used because as per the docs:  http://extentreports.relevantcodes.com/java/version2/docs.html#create-step-logs... 

Different log types create different number of columns, which results in malformed HTML.  If you mix different log types, below is what happens:

<table>
	<tr>
		<td>Timestamp</td>
		<td>Status</td>
		<td>Details</td>
	</tr>
	<tr>
		<td>Timestamp</td>
		<td>Status</td>
		<td>StepName</td>
		<td>Details</td>
	</tr>
</table>

Once you use stepName, use it for all your logs otherwise HTML will break and you will receive the following message.  I will fix this so it doesn't stop execution but the test's table will have several null cells.

**Comment by subratkumarmandal** [comment]
Thanks ! let me correct my logs to be consistent and see if this error doesn't happens.

**Comment by subratkumarmandal** [comment]
One more thing I take screenshots on failure hence how to show throwable and screenshot both in the log details.

**Comment by anshooarora** [comment]
You will have to use 2 logs when this happens:

```
test.log(status, throwable);
test.log(status, test.addScreenCapture("screenshot-path"));
```

**Comment by vertissachin** [comment]
hi ansho,

please let us know when this fix will be available in release.

Thanks,
Sachin

**Comment by karthikbhatnagar** [comment]
Sachin the latest is 2.40.1 beta. You can try that.

**Comment by vertissachin** [comment]
yes latest one is 2.40.1 but its not taking in maven dependency.i thinks you have't created dependency for latest version

**Comment by karthikbhatnagar** [comment]
I have noticed Anshoo rarely created snapshot version.  You can manually add jar and test at least your test will work as expected

**Comment by vertissachin** [comment]
OK thanks but when its dependency will be available?

**Comment by vertissachin** [comment]
Hi Ansho,

i have a question how to generate the reports when we run the test in multibrowser at the same time ,
actulay we are running the test on multiple browser using xml file like

 <test name="WIN8_Chrome46">
        <parameter name="browser" value="chrome" />
        <parameter name="platform" value="WIN8" />
        <parameter name="version" value="46" />
        <classes>
            <class name="test1" />           
        </classes>
    </test>

    <test name="WIN8_Firefox37">
        <parameter name="browser" value="firefox" />
        <parameter name="platform" value="WIN8" />
        <parameter name="version" value="37" />
        <classes>
            <class name="test2" />           
        </classes>
    </test>

but after running the test i am getting the only last browser result in html file.
so could you please help to generate report for multibrowser run 

thanks ... !!!

**Comment by vertissachin** [comment]
Hi Ansho,

i have a question how to generate the reports when we run the test in multibrowser at the same time. actulay we are running the test on multiple browser using xml file like
 <test name="WIN8_Chrome46">
        <parameter name="browser" value="chrome" />
        <parameter name="platform" value="WIN8" />
        <parameter name="version" value="46" />
        <classes>
            <class name="test1" />           
        </classes>
    </test>

    <test name="WIN8_Firefox37">
        <parameter name="browser" value="firefox" />
        <parameter name="platform" value="WIN8" />
        <parameter name="version" value="37" />
        <classes>
            <class name="test2" />           
        </classes>
    </test>

but after running the test i am getting the only last browser result in html file.
so could you please help to generate report for multibrowser run 

thanks ... !!!

**Comment by yolch-yolchyan** [comment]
Hello,
When 2.40.1 will be available on maven repo. It's already two years has been passed from this post.

**Comment by amitpatel1729** [comment]
Hello, 

I am using -  <dependency>
			<groupId>com.relevantcodes</groupId>
			<artifactId>extentreports</artifactId>
			<version>2.41.2</version>
		   </dependency>

Issue - When i run in test my local it's working and generates  the html report. but while running test on cloud environment (test object) , getting the error while flush() report. 

Exception -  2018-07-12 11:00:53 ERROR runtime:60 - Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> report.systemInfoMap[info]  [in template "Extent.ftl" at line 193, column 95]

----
Tip: It's the final [] step that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${report.systemInfoMap[info]}  [in template "Extent.ftl" at line 193, column 93]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
	at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:240)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at freemarker.template.Template.process(Template.java:325)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:173)
	at com.relevantcodes.extentreports.Report.flush(Report.java:468)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:900)
	at com.relevantcodes.extentreports.Report.terminate(Report.java:435)
	at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:917)
	at com.care.common.BaseTest.afterSuiteConfig(BaseTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

**Comment by amitpatel1729** [comment]
@anshooarora please help us to resolve the issue
