### ISSUE TITLE
Getting error while running the script in testNG

### ISSUE THREAD

**Issue by cybkishor** [anshooarora/extentreports#197]
Getting below error
[TestNG] Running:
  C:\Users\knaik\AppData\Local\Temp\testng-eclipse--2096791152\testng-customsuite.xml

Dec 09, 2015 8:06:39 AM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/C:/Users/knaik/Desktop/Audit/extentreports-java-v2.40/extentreports-2.40.0/extentreports-java-2.40.0.jar!/com/relevantcodes/extentreports/resources/extent-config.xml
FAILED CONFIGURATION: @AfterMethod tearDown([TestResult name=tc1 status=FAILURE method=ReportTest.tc1()[pri:0, instance:testScripts.ReportTest@18d1cf9e] output={null}])
java.lang.NullPointerException
	at testScripts.ReportTest.tearDown(ReportTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

FAILED: tc1
java.lang.NoClassDefFoundError: freemarker/template/TemplateModelException
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:84)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:230)
	at testScripts.ReportTest.tc1(ReportTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ClassNotFoundException: freemarker.template.TemplateModelException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
    Configuration Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
Configuration Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.XMLReporter@54eaa827: 12 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 6 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@65312942: 10 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@54594d1d: 41 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@163202d6: 31 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@34d68841: 9 ms

**Comment by anshooarora** [comment]
Have you manually added Extent to your project? Are all dependencies added, freemarker in this case?

**Comment by cybkishor** [comment]
i have added all the jars manually .

My Program:
package testScripts;


import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriver.Timeouts;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.*;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;


import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;


public class ReportTest {	
	ExtentReports report;
	ExtentTest extentre;
	WebDriver driver;
	
@Test
public void tc1()
{
	report = new ExtentReports("D:\\ExtentReport\\Report.html");
	report.startTest("Verify the title");
	driver = new FirefoxDriver();
	driver.get("http://www.google.com");
	driver.manage().window().maximize();
	extentre.log(LogStatus.INFO, "Browser Launched");
	driver.manage().timeouts().implicitlyWait(5000 ,TimeUnit.SECONDS);
	String name = driver.getTitle();
	Assert.assertTrue(name.contains("Google"));
	extentre.log(LogStatus.PASS, "Title verified");
}

@AfterMethod
public void tearDown(ITestResult result)
{
   if(result.getStatus()==ITestResult.SUCCESS)
   {
	   extentre.log(LogStatus.INFO, "Inside Success");
   }
   
   report.flush();
   report.close();
  
	//driver.get("D:\\ExtentReport\\Report.html");
}
}


Error Log:
[TestNG] Running:
  C:\Users\knaik\AppData\Local\Temp\testng-eclipse-1005541573\testng-customsuite.xml

Dec 10, 2015 12:23:57 AM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/C:/Users/knaik/Desktop/Audit/extentreports-java-v2.40/extentreports-2.40.0/extentreports-java-2.40.0.jar!/com/relevantcodes/extentreports/resources/extent-config.xml
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
FAILED: tc1
java.lang.NullPointerException
	at testScripts.ReportTest.tc1(ReportTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@563af8a6: 79 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 12 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@12413ffc: 9 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@5a9f0e68: 9 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@2f616fcf: 7 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@642a590d: 64 ms

**Comment by cybkishor** [comment]
The program runs in browser but no reports generated in the file path given.

**Comment by anshooarora** [comment]
You were missing this:

```
extentre = report.startTest("Verify the title");
```

**Comment by cybkishor** [comment]
Thanks a lot , it works now

**Comment by cybkishor** [comment]
What is the listener name needs to be used if we want to run from xml & testNG
<?xml version="1.0" encoding="UTF-8"?>
<suite name="SuiteName">
    <listeners>
        <listener class-name="" />
    </listeners>
    <test name="SystemWithoutReqFuntions">
     <classes>
         <class name="testScripts.ReportTest"></class>
     </classes>
 </test>
</suite>

**Comment by abhicoolsince88** [comment]
hi i am getting an  error while running the extentReport script  , please find the
 error below

FAILED CONFIGURATION: @AfterMethod tearDown([TestResult name=verifyTitle status=FAILURE method=Reports.verifyTitle()[pri:0, instance:Reports@18be83e4] output={null}])
java.lang.Error: Unresolved compilation problem: 
	This method must return a result of type String

**Comment by abhicoolsince88** [comment]
please help on it

**Comment by nitishkumar2010** [comment]
Hi Anshoo,

I m getting below error and browser is also not opening in this case,

FAILED CONFIGURATION: @AfterMethod tearDown([TestResult name=verifyPageTitle status=FAILURE method=ExtentReportsDemo2.verifyPageTitle()[pri:0, instance:ExtentReportsPart2.ExtentReportsDemo2@6979e8cb] output={null}])
java.lang.NullPointerException
	at ExtentReportsPart2.ExtentReportsDemo2.tearDown(ExtentReportsDemo2.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

FAILED: verifyPageTitle
java.lang.NoClassDefFoundError: freemarker/template/TemplateException
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:84)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:418)
	at ExtentReportsPart2.ExtentReportsDemo2.verifyPageTitle(ExtentReportsDemo2.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ClassNotFoundException: freemarker.template.TemplateException
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 27 more


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
    Configuration Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
Configuration Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.XMLReporter@1eb44e46: 24 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@cac736f: 11 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@726f3b58: 37 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 11 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@1edf1c96: 57 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@7de26db8: 7 ms


*************************************************
Below is the code for the same:-

@Test
	public void verifyPageTitle(){
		
		report = new ExtentReports("D:\\NitishReport\\Reports.html");
		report.startTest("Verify the title");
		
		driver = new FirefoxDriver();
		driver.manage().window().maximize();
		
		extentTest.log(LogStatus.INFO, "Browser Started");
		
		driver.get("https://www.google.co.in/");
		
		extentTest.log(LogStatus.INFO, "Application Started");
		
		String title = driver.getTitle();
		Assert.assertTrue(title.contains("Google"));

		extentTest.log(LogStatus.PASS, "Test Passed");
		
	}
	
	
	@AfterMethod
	public void tearDown(ITestResult result){
		
		if(result.getStatus() == ITestResult.FAILURE)
		{
			String screenshotPath = Utility.takeScreenShot(driver, result.getName());
			System.out.println(result.getName() + " and "+ screenshotPath);
			
			String image = extentTest.addScreenCapture(screenshotPath);
			extentTest.log(LogStatus.FAIL, "Test Failed", image);
		}
		
		report.endTest(extentTest);
		report.flush();
		
		driver.get("D:\\NitishReport\\Reports.html");
	}
	


It seems that it is throwing this error in "**report = new ExtentReports("D:\\NitishReport\\Reports.html")"** and thats why it is throwing null pointer exception for webdriver.

Please help here.
