### ISSUE TITLE
getting below exception while running report

### ISSUE THREAD

**Issue by anil339597** [anshooarora/extentreports#213]
com.relevantcodes.extentreports.ExtentTestInterruptedException: Close was called before test could end safely using EndTest.
at com.relevantcodes.extentreports.Report.terminate(Report.java:174)
at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:508)
at com.schneiderElectric.utils.ReportsUtil.closeReporter(ReportsUtil.java:33)
at com.schneiderElectric.Product_EcoSystems_Test.TC_001.TestCase1(TC_001.java:107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:617)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)

**Comment by anshooarora** [comment]
See [here](http://extentreports.relevantcodes.com/java/version2/docs.html#close-extent) for an explanation.

**Comment by testphreak** [comment]
@anshooarora I have been seeing this exception _intermittently_ in the last few runs with v2.41.1. Looks like the page you linked to is dead. Can you update it? Nothing's changed in the logic integrating ExtentReports into my test framework recently. So I am curious what could be causing the issue.

```java
com.relevantcodes.extentreports.ExtentTestInterruptedException: Close was called before test could end safely using EndTest.
	at com.relevantcodes.extentreports.Report.terminate(Report.java:421)
	at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:920)
	at com.axiom.turbo.webdriver.BaseTest.closeExtentReports(BaseTest.java:404)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:336)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```
Here's the corresponding ```closeExtentReports``` method.

```java
    /**
     * Close ExtentReports
     */
    @AfterSuite(alwaysRun = true)
    public void closeExtentReports() {
        //log output of tests to TestRunner logs view of ExtentReports html file
        //Added a LinkedHashSet to filter out duplicates (TestNG ISuiteListener.onStart() bug) in list while preserving order
        //https://github.com/cbeust/testng/issues/171
        //May have the unintended consequence of non-unique log statements missing from test runner logs view in report
        Set<String> deDuplicatedReporterOutput = new LinkedHashSet<>(Reporter.getOutput());
        for (String s : deDuplicatedReporterOutput) {
            ExtentReporter.getExtent().setTestRunnerOutput(s);
        }
        ExtentReporter.getExtent().close();
    }
```

**Comment by anshooarora** [comment]
I would suggest removing `close` altogether.  In the next version, this method won't be available.

**Comment by SandipanBhattacharjee** [comment]
Hi Anshoo..

Thanks a lot your direction worked like charm..

But how do i combine multiple reports together.. do u have any suggestions
for that..

Thanks again
Sandipan.

On Aug 7, 2016 8:01 PM, "Anshoo Arora" <notifications@github.com> wrote:
>
> I would suggest removing close altogether. In the next version, this
method won't be available.

**Comment by jayshreekant** [comment]
Dear Anshu,
I am getting below exception everytime, 
com.relevantcodes.extentreports.ExtentTestInterruptedException: Close was called before test could end safely using EndTest.

Because of this exception, my complete logs are not reflecting in the reports, and only 1 testcase is getting passed out of 13 countries, I am using your testng example in my reports. Please revert me for this issue as soon as possible 
![screenshot_2](https://cloud.githubusercontent.com/assets/12380291/17846534/cd46c560-6866-11e6-85c7-fd567e860654.jpg)

**Comment by anshooarora** [comment]
@jayshreekant -  please open a new ticket and share your code.

**Comment by anand853** [comment]
we have the same issue.
