### ISSUE TITLE
Exception occured at  extent.flush(); when removing Extenttest.log(LogStatus.INFO, "Mobile No" + " : " + mobileNumber.toString());

### ISSUE THREAD

**Issue by raviacin** [anshooarora/extentreports#214]
FreeMarker template error:
The following has evaluated to null or missing:
==> log.stepName  [in template "Extent.Offline.ftl" at line 297, column 93]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${log.stepName}  [in template "Extent.Offline.ftl" at line 297, column 91]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
	at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at freemarker.template.Template.process(Template.java:325)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:151)
	at com.relevantcodes.extentreports.Report.flush(Report.java:213)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:491)
	at ConsumerAppParallelExecution.executeParallelTestCase(ConsumerAppParallelExecution.java:119)
	at MobileTest.main(MobileTest.java:59)
java.lang.NullPointerException
	at java.io.Writer.write(Unknown Source)
	at com.relevantcodes.extentreports.utils.Writer.write(Writer.java:21)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:164)
	at com.relevantcodes.extentreports.Report.flush(Report.java:213)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:491)
	at ConsumerAppParallelExecution.executeParallelTestCase(ConsumerAppParallelExecution.java:119)
	at MobileTest.main(MobileTest.java:59)

**Comment by anshooarora** [comment]
Duplicate as #190.  Fix will be available in the next release.

**Comment by vertissachin** [comment]
Hi  when the next release/fix will be available or is it merged in latest release 2.40. if not then what is the maven dependency we will used for getting this fix.
