### ISSUE TITLE
java.lang.NoClassDefFoundError: freemarker/ext/beans/BeansWrapperBuilder

### ISSUE THREAD

**Issue by rakslalsangi** [anshooarora/extentreports#217]
I am getting below exception when I am using extent report 2.40 

java.lang.NoClassDefFoundError: freemarker/ext/beans/BeansWrapperBuilder

**Comment by anshooarora** [comment]
Do you have all dependencies associated with your project?  This is for freemarker.jar.

**Comment by rakslalsangi** [comment]
Yes I have all dependencies related to my project . I am getting this issue when I add latest jar file of extent report 2.40 , for extent report 2.10  it works fine .

First I worked for extent report 2.10 everything working fine , and when I add extent report 2.40 , I am getting this error .

**Comment by anshooarora** [comment]
Remove 2.10 and all of its dependencies.  Perform a [clean build](http://stackoverflow.com/questions/6803322/how-to-achieve-that-eclipse-clean-and-build-aka-rebuild) with 2.40.

**Comment by rakslalsangi** [comment]
I created new project and added extent report 2.40 jar , still I am getting this error .
I written fresh new code  and added extend report 2.40 , and run , getting same error .

Error - 

java.lang.NoClassDefFoundError: freemarker/template/TemplateException
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:84)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:230)
	at ExtentDemo8.name1(ExtentDemo8.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ClassNotFoundException: freemarker.template.TemplateException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 27 more

**Comment by anshooarora** [comment]
If you have freemarker, jsoup and sqlite added then, can you try with the following dependency (xml-apis) as shown in this ticket:     https://github.com/anshooarora/extentreports/issues/187.

**Comment by rakslalsangi** [comment]
Hi Anshoo ,

I have this jar files -  freemaker  2.3.15 ,  jsoup 1.8.3  ,  xml-apis 1.4.01  ,  sqlite  , and other supporting jars , now I am getting different error .

java.lang.NoClassDefFoundError: freemarker/ext/beans/BeansWrapperBuilder

Console error - 

Dec 30, 2015 10:13:35 AM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/C:/Users/admin/Downloads/extentreports-2.40.jar!/com/relevantcodes/extentreports/resources/extent-config.xml
FAILED: test
java.lang.NoClassDefFoundError: freemarker/ext/beans/BeansWrapperBuilder
	at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:69)
	at com.relevantcodes.extentreports.Report.attach(Report.java:96)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:84)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:213)
	at test.Demo.test(Demo.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ClassNotFoundException: freemarker.ext.beans.BeansWrapperBuilder
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 29 more
