### ISSUE TITLE
Script failing in Pool server or Jenkins

### ISSUE THREAD

**Issue by jaingajendra** [anshooarora/extentreports#235]
Hi

I am using the Extent report in my selenium framework. Its working fine locally.
But when it is executed remotely or in pool server, I am getting the following exception

Running TestSuite
Configuring TestNG with: TestNG652Configurator
log4j:WARN Please initialize the log4j system properly.
log4j:WARN No appenders could be found for logger (com.wirelesscar.vehiclesettings.report.DetailedLogs).
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.io.FileNotFoundException: /home/wcar_op\extentreports\css\css.css (Permission denied)
at com.relevantcodes.extentreports.ReportInstance.initOfflineMode(ReportInstance.java:192)
at com.relevantcodes.extentreports.support.Resources.moveResource(Resources.java:29)
at java.io.FileOutputStream.(FileOutputStream.java:101)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.(FileOutputStream.java:213)
at com.relevantcodes.extentreports.ExtentReports.(ExtentReports.java:77)
at com.relevantcodes.extentreports.ExtentReports.(ExtentReports.java:45)
at com.wirelesscar.vehiclesettings.GuiBaseConf.TestBase.(TestBase.java:63)

java.io.FileNotFoundException: /home/wcar_op\extentreports\css\font-awesome.css.map (Permission denied)

java.io.FileNotFoundException: /home/wcar_op\extentreports\css\fontawesome-webfont.eot (Permission denied)

Could you please let me know where i am makiing a mistake.

Regards,
Gajendra

**Comment by anshooarora** [comment]
Is this the same issue as #234?
