### ISSUE TITLE
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.  on .Net - v2.40.1-beta2

### ISSUE THREAD

**Issue by mittt** [anshooarora/extentreports#241]
I got this exception on a EndTest(test). The test report was written successfuly and it inclueds the test in question.

Sorry, I can't provide sample project, replicating the issue. I will try to tell what ever information I can share: My report contains 75 tests with many steps, each. The tests run in parallel on 15 threads. I use NUnit 3.0.0 to run those. Those tests are Selenium tests, 5 scenarious, that run on 15 machines.

I just updated the lib from 2.0.2 to v2.40.1-beta2. 

I'm sharing this because, it sound's like a bug. I'm not sure if it will happen next run.

```
1) Error : WebTests.Tests.RunTests(RMHub CHROME_WIN8_1).RunUnitTests
TearDown : System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
--TearDown
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at CompiledRazorTemplates.Dynamic.RazorEngine_173864cca8cf4b8195a3e9c52ca1e444.Execute()
   at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context, TextWriter reader)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RelevantCodes.ExtentReports.HTMLReporter.AddTest()
   at RelevantCodes.ExtentReports.Model.Report.<AddTest>b__2(IReporter x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at RelevantCodes.ExtentReports.Model.Report.AddTest(Test Test)
   at RelevantCodes.ExtentReports.ExtentReports.EndTest(ExtentTest Test)
   at WebTests.Tests.TestRunnerBase.TearDown() in d:\Program Files (x86)\Jenkins\jobs\RM APP Build and Test\workspace\SauceLabs_SeleniumProject\TestRunnerBase.cs:line 93
```

PS: On a side note, after updating the lib, the report size jumped from ~9MB to 26.70 MB.

**Comment by anshooarora** [comment]
I will investigate this, especially as all my tests are from perspective of NUnit versions 2 and no parallel tests performed.

The size will considerably reduce once the file is minified.  Will uncomment this line in the next release:  https://github.com/anshooarora/extentreports/blob/master/dotnet/RelevantCodes.ExtentReports/RelevantCodes.ExtentReports/View/Extent.cs#L610

**Comment by anshooarora** [comment]
Question: I have never done this before with NUnit.  Are you running fixtures in parallel or methods?  

This is what you are using, correct?  https://github.com/nunit/dev/wiki/Framework-Parallel-Test-Execution

**Comment by mittt** [comment]
Yes, that's the thing.

I use the [Parallelizable(ParallelScope.Self)] option. 

But ExtentReports instance is created in   
  [SetUpFixture]
    public class SetUpFixtureBase
    { ....

This class runs once, before all tests.

I'll try to update this post tomorol, i'm in a hurry, now.

**Comment by anshooarora** [comment]
Found the issue(s),  will release a fix.

**Comment by anshooarora** [comment]
Beta-3 is out, can you please test with it and see if you still face this issue?

**Comment by mittt** [comment]
Beta-3 is broken:
GET file:///C:/Users/Anshoo/git/extentreports/cdn/extent.js net::ERR_FILE_NOT_FOUND

I guess this shouldn't have ended in the commit:
<script src='file:///C:/Users/Anshoo/git/extentreports/cdn/extent.js'>

**Comment by mittt** [comment]
Also,  I got the following error with the old version(beta 2), but i guess it may have been fixed:

1) TearDown Error : WebTests.Tests.SetUpFixture
One or more child tests had errors
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
--TearDown
   at RelevantCodes.ExtentReports.Model.Report.<Terminate>b__6(ExtentTest x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at RelevantCodes.ExtentReports.Model.Report.Terminate()
   at RelevantCodes.ExtentReports.ExtentReports.Close()
   at WebTests.Tests.SetUpFixtureBase.BaseRunAfterAnyTests() in d:\Program Files (x86)\Jenkins\jobs\RM APP Build and Test\workspace\SauceLabs_SeleniumProject\SetUpFixtureBase.cs:line 43
   at WebTests.Tests.SetUpFixtureBase.RunAfterAnyTests() in d:\Program Files (x86)\Jenkins\jobs\RM APP Build and Test\workspace\SauceLabs_SeleniumProject\SetUpFixtureBase.cs:line 57

**Comment by anshooarora** [comment]
Yes, this issue was fixed.  It was caused by some resources being modified by multiple threads at once.  I was able to reproduce using Nunit 3.
