### ISSUE TITLE
Getting java.sql.SQLException while writing result to DB

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#259]
Hi Anshoo,

I am getting below exception while writing results to DB,could you please help 

```
java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: Test.TestIDExtent)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.execute(DB.java:810)
	at org.sqlite.core.DB.executeUpdate(DB.java:847)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:86)
	at com.relevantcodes.extentreports.DBReporter.addTest(DBReporter.java:305)
	at com.relevantcodes.extentreports.Report.addTest(Report.java:131)
	at com.relevantcodes.extentreports.Report.terminate(Report.java:180)
	at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:508)
	at mob.atg.util.MAU_TestRunnerHelper.afterSuite(MAU_TestRunnerHelper.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

**Comment by anshooarora** [comment]
Version?

**Comment by jawlitkp** [comment]
2.40.0

**Comment by jawlitkp** [comment]
i am deleting db file every time before running my test ,so assuming it is getting created by version 2.40

**Comment by jawlitkp** [comment]
@AfterSuite(alwaysRun=true)
	public void afterSuite() {
		report.flush();
		report.close();
	}
	@AfterMethod(alwaysRun=true)
	public void afterTest(ITestResult result){
		if (result.getStatus() == ITestResult.FAILURE) {
			reporter.log(LogStatus.FAIL, "<pre>" + result.getThrowable().getMessage() + "</pre>"+ reporter.addScreenCapture(takeScreenShot("failedFromAfterMethod")));
		}        
		report.endTest(reporter);
		
		if(config.get("closebrowser").equals("Y")){
			Long threadID = Thread.currentThread().getId();
			threadDriver = (WebDriver) paramMap.get(threadID).get("Driver");
			if(threadDriver!=null){
				if(currentDeviceBrowser.equals(BBBU_Constants.DEVICE_IPHONE6))
				{
				threadDriver.close();
			    threadDriver.quit();
				}
			}
		}
		//report.flush();

	}
	@AfterTest(alwaysRun=true)
	public void tear(){
//		if(config.get("closebrowser").equals("Y")){
//			Long threadID = Thread.currentThread().getId();
//			threadDriver = (WebDriver) paramMap.get(threadID).get("Driver");
//			if(threadDriver!=null){
//				//threadDriver.close();
//				//threadDriver.quit();
//			}
//		}
	}

	public void initReporter() {
		report = getReporterInstance();
		report.startReporter(ReporterType.DB, System.getProperty("user.dir")+"//result.db");
		reporter = report.startTest(
				currentTestCase + "_" + currentConcept + "_" + currentDeviceBrowser,
				currentTestSuite).assignCategory(currentTestSuite,
						currentConcept, currentDeviceBrowser);
	}

	public ExtentReports getReporterInstance() {

		if (report == null) {
			report = new ExtentReports(System.getProperty("mobAtgHtmlReportFolderNamePath")+"//"+"Results.html", true);

		}
		return report;
	}

**Comment by anshooarora** [comment]
I am able to reproduce..  Its because I have set the ID as primary key [here](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/DBReporter.java#L99).  Will release a fix, will also be available in beta-4.

**Comment by jawlitkp** [comment]
awesome ,thanks.
