### ISSUE TITLE
Random System.NullReferenceException on Close with extentreports-net-v2.40.1-beta3b

### ISSUE THREAD

**Issue by mittt** [anshooarora/extentreports#271]
I got this error on .Close: 

TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
--TearDown
   at RelevantCodes.ExtentReports.Model.Report.<Terminate>b__8(ExtentTest x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at RelevantCodes.ExtentReports.Model.Report.Terminate()
   at RelevantCodes.ExtentReports.ExtentReports.Close()
   at WebTests.Tests.SetUpFixtureBase.BaseRunAfterAnyTests() in d:\Program Files (x86)\Jenkins\jobs\RM APP Build and Test\workspace\SauceLabs_SeleniumProject\SetUpFixtureBase.cs:line 43
   at WebTests.Tests.SetUpFixtureBase.RunAfterAnyTests() in d:\Program Files (x86)\Jenkins\jobs\RM APP Build and Test\workspace\SauceLabs_SeleniumProject\SetUpFixtureBase.cs:line 57

I think all my tests have errored, so this report should have contained 75 Errored tests.

**Comment by anshooarora** [comment]
Are you calling close after each test?  How can I reproduce?

**Comment by mittt** [comment]
I'm calling EndTest on each test. Close is called on the whole report, only once, after all tests. 

I'm not sure how to reproduce it. This has happend only, once.

**Comment by anshooarora** [comment]
Beta-4 has a few fixes/changes, its also available on Nuget.  Please try with this build.

I am closing this for now but feel free to open if you encounter this issue again.
