### ISSUE TITLE
java.lang.NoClassDefFoundError: freemarker/template/TemplateModelException

### ISSUE THREAD

**Issue by mailtokyatham** [anshooarora/extentreports#295]
I am using extentreports-java-2.40.1-beta5-final jar and following code to 

	extent=new ExtentReports(sPath, new Locale("es"));
		extent.loadConfig(ExtentReports.class,"D:\\Work\\Softwares\\extentreports-java-v2.40.1-beta5-final\\extent-config.xml");
test= extent.startTest("Launch Application");
		test.assignCategory("BVT");
		
		System.setProperty("webdriver.chrome.driver", "D:\\eclipse\\workspace\\Drivers\\chromedriver.exe");
		
		 driver = new ChromeDriver();
		test.log(LogStatus.INFO, "Browser Up and Running...");
		
		driver.get("http://www.seleniumhq.org/");
		test.log(LogStatus.INFO, "Application has been launched....");

***************************************************************************************************
Its not executing and throwing following error , anything missing here?

java.lang.NoClassDefFoundError: freemarker/template/TemplateModelException
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:77)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:389)
	at scripts.ReportClass.beforeClass(ReportClass.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ClassNotFoundException: freemarker.template.TemplateModelException

**Comment by anshooarora** [comment]
Have you added the required jars?  Freemarker in this case.

**Comment by mailtokyatham** [comment]
Do we need to add freemaker jars?

**Comment by anshooarora** [comment]
Yes, it should be in the lib folder if you have download it from the website.  Maven will add them automatically.

**Comment by amolppatil92** [comment]
i am using extent reports and in that i am trying to customize log which were generated by extent reports
below are the classes for that:
1)
public class Utility  
{
	ExtentTest logger = new ExtentTest("TestCase", "Description");
	
	public static String CaptureScreenshot(WebDriver driver, String screenshotName)
	{
		
		try 
		{
			TakesScreenshot ts=(TakesScreenshot)driver;
			File source=ts.getScreenshotAs(OutputType.FILE);
			FileUtils.copyFile(source,new File ("C://Users//PatilA06//workspace//NewExtentReports//src//Screenshots"+screenshotName+".png"));
			System.out.println("Screenshots taken");
		} 
		catch (Exception e)
		{
			System.out.println("Exception while taken Screenshots"+e.getMessage());
			return e.getMessage();
		}
		return screenshotName;
			
	}
	


	public void logReporter(String step, String inputValue,String expectedValue, String actualValue,LogStatus status)
	{
		int counter = 1;
		String filename = "step"+counter+".png";
		String Filepath = "C://Users//PatilA06//workspace//NewExtentReports//Reports//Screenshot";
		String logString = step+"|| Input Value : "+inputValue+" || Expected Result : "+expectedValue+" || Actual Result : "+actualValue;
		if(status == LogStatus.PASS)
		{
			logger.log(LogStatus.PASS, logString);
			Assert.assertTrue(true);
		}	
	}

}

2)
public class AutoReport extends Utility
{
	ExtentReports report;
	
	WebDriver driver;
	Utility objUtility = new Utility();
	

  @Test
  public void Verify_Title()
  {
	  report=new ExtentReports("C://Users//PatilA06//workspace//NewExtentReports//src//scripts//AdvanceReport.html");
	  logger=report.startTest("Test_VerifyTitle");		   
	  driver=new FirefoxDriver();		   
	  driver.manage().window().maximize();		   
	 // logger.log(LogStatus.INFO,"Browser Started");		   
	  driver.get("http://www.google.com");		  	  
	  String title=driver.getTitle();	
	  if(title.equalsIgnoreCase("Google"))
	  objUtility.logReporter("Verfiy Title","","Title Should be Google","Title is verified successfully",LogStatus.PASS);
	 // Assert.assertTrue(title.contains("Google"));
	  report.endTest(logger);

  }
}
when i end up with execution in html file i.e(reports file) log are not getting generated.
Atached is the zipped html file.

Thanks in advance

**Comment by mailtokyatham** [comment]
Hi Anshoo,

I would like to thank you for extent report which makes my life easier .

I have couple of clarifications on extent merge functionality.

Issue1) Attached IndividualReport.png file which is individual report ,
when I use extent merge for summary , its not showing the data as in
individual reports(color, ..ect)

Attached Merge_Report.png for your reference.

Issue2) Issues_in_merge_report.png attached , please open the same and
clarify the questions over there.


Issue3) I see ? in merge report , when I give space between words in
individual report.



13:09:12 Sheet4� Not Found in
15678_EMIRExtract_0000_20151001_20151031_42545.xls�Hence Skipped for
Comparision


Issue4) I am comparing the two excels where excel files contains no.of
sheets, in result file sheets shows as test , i dont want to show this as
test, (I have added this as child test)

Attached html  file for reference.


Configuration :

extentreports-java-2.40.1-beta5-final.jar
extentmerge.jar

Jdk : 1.7

let me know if you need any information.

Regards
Srinivas

**Comment by ArunShanmukha** [comment]
Hi Guys, 

I' am facing the similar issue related to extent report. Can anybody help me please.
i have the maven dependency for extent report along with freemaker maven dependency.
And i'm getting following error mentioned below:



************************************************************************************
[TestNG] Running:
  C:\Users\inashanmuk\AppData\Local\Temp\testng-eclipse--909774827\testng-customsuite.xml

FAILED CONFIGURATION: @BeforeMethod launchapplication
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.relevantcodes.extentreports.Configuration.getConfigurationMap(Configuration.java:38)
	at com.relevantcodes.extentreports.Report.loadConfig(Report.java:474)
	at com.relevantcodes.extentreports.Report.<init>(Report.java:611)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:74)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:141)
	at courierApps.TestDefinition.SignUp_and_Activation.LoginAndActivation.launchapplication(LoginAndActivation.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 more 

***************************************************************************************

Maven dependency:

 
	    <dependency>
	      <groupId>com.relevantcodes</groupId>
	      <artifactId>extentreports</artifactId>
	      <version>2.41.2</version>
	    </dependency>
	    
		<dependency>
		    <groupId>org.freemarker</groupId>
		    <artifactId>freemarker</artifactId>
		    <version>2.3.23</version>
		</dependency>

********************************************************************************************
********************************************************************************************
********************************************************************************************


The following testNG code for Appium : 

package courierApps.TestDefinition.SignUp_and_Activation;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import java.util.Properties;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.DisplayOrder;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import com.relevantcodes.extentreports.NetworkMode;

import courierApps.com.aditi.qa.trainings.controlsAndBusinessLogics.DashBoardPage_Common;
import courierApps.com.aditi.qa.trainings.controlsAndBusinessLogics.LoginPage_Common;
import courierApps.com.aditi.qa.utilities.ActionUtility;
//import courierApps.com.aditi.qa.utilities.Constant;

public class LoginAndActivation {

	ExtentReports report;
    ExtentTest test; 
    //ExtentTest logger;
	private static AppiumDriver<MobileElement> driver;
	Properties p = new Properties();
    FileInputStream fis = null;
    DashBoardPage_Common dashBoard = new DashBoardPage_Common();
    LoginPage_Common loginPage = new LoginPage_Common();
    public static String workingDir = System.getProperty("user.dir");
    public String Path_Report = workingDir + "//extent-report//";
    private static ActionUtility actionUtility = new ActionUtility();
    
	@BeforeMethod
	public void launchapplication() throws Exception {
//		report = new ExtentReports("F:\\Appium_WorkSpace\\TestMaven\\Extent_Report\\Mobile_Android_Report.html");
		
		report = new ExtentReports("F:\\reportExtent\\Mobile_Android_Report.html", false, DisplayOrder.OLDEST_FIRST, NetworkMode.ONLINE);
		
		
		test = report.startTest("LoginAndActivation");
		try {
			fis = new FileInputStream("./DataSource/Data.Properties");
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		p.load(fis);
		Thread.sleep(500);
		File app = new File(p.getProperty("ApplicationPath"));
		  DesiredCapabilities capabilities = new DesiredCapabilities();
		  capabilities.setCapability("deviceName",p.getProperty("AndroidDeviceName"));
		  capabilities.setCapability(CapabilityType.VERSION, p.getProperty("AndroidPlatformVersion"));
		  capabilities.setCapability(CapabilityType.PLATFORM, p.getProperty("platformName"));
		  capabilities.setCapability("noReset", true);
		  capabilities.setCapability("app", app.getAbsolutePath());
		  capabilities.setCapability("package", p.getProperty("AppPackage"));
		  capabilities.setCapability("app-wait-activity", "activity-to-wait-for");
		  driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
		  driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		  dashBoard.setDriver(driver);
		  loginPage.setDriver(driver);
	}
	
	/*
	 * Activation process
	 */
	
	@Test(groups ={"smoke","p1"})
	public void LC1085_VerifyTheActivationScreenDisplayed() throws Exception{
		test = report.startTest("LC1085_VerifyTheActivationScreenDisplayed");  
		try{
			
			test.log(LogStatus.INFO,"Courier App Started...");
			//loginPage.beforeExtentReport("LC1085_VerifyTheActivationScreenDisplayed");
			loginPage.verifyTheActivateButtonIsDisplayedInLoginPage();
			
		}catch(Exception e){
			throw e;
		}
	}

    @AfterMethod
    public void endApplication() throws Exception{
    	driver.quit();
    	
    	report.endTest(test);
 		report.flush();
    	
    }
}
