### ISSUE TITLE
java.lang.NoSuchMethodError for 2.40.1

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#297]
Hi Ansho,

I am getting below exception for new jar file ,please take a look 

java.lang.NoSuchMethodError: com.relevantcodes.extentreports.model.Test.setLog(Lcom/relevantcodes/extentreports/model/Log;)V
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:95)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:176)
	at com.bbb.util.BBBU_ExtentTest.log(BBBU_ExtentTest.java:13)
	at dsk.tbs.util.DTU_PageHelper.mLaunchConcept(DTU_PageHelper.java:97)
	at dsk.tbs.sanity.s13899SearchBar.searchBar(s13899SearchBar.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

here is my code 

package com.bbb.util;

import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class My_ExtentTest {

	
	public ExtentTest extentReporter;
	
	public void log(LogStatus logstatus,String details)
	{
		extentReporter.log(logstatus, details);
		if(logstatus.equals(LogStatus.INFO) || logstatus.equals(LogStatus.PASS))
		{
		   Log.info(details);
		}else if(logstatus.equals(LogStatus.FAIL))
		{
			Log.fail(details);
		}else if(logstatus.equals(LogStatus.FATAL))
		{
			Log.fatal(details);
		}else if(logstatus.equals(LogStatus.WARNING))
		{
			Log.warn(details);
		}
	}
	
	
	public void log(LogStatus logstatus,Throwable t)
	{
		extentReporter.log(logstatus, t);

		if(logstatus.equals(LogStatus.INFO) || logstatus.equals(LogStatus.PASS))
		{
		   Log.info(t);
		   t.printStackTrace();
		}
		else if(logstatus.equals(LogStatus.FAIL))
		{
			Log.fail(t);
			t.printStackTrace();
		}else if(logstatus.equals(LogStatus.FATAL))
		{
			Log.fatal(t);
			t.printStackTrace();
		}else if(logstatus.equals(LogStatus.WARNING))
		{
			Log.warn(t);
			t.printStackTrace();
		}
		
	}
	
	
	public void log(LogStatus logStatus,String stepName,String details )
	{
		extentReporter.log(logStatus, stepName, details);
		
		if(logStatus.equals(LogStatus.INFO) || logStatus.equals(LogStatus.PASS))
		{
		   Log.info("Stepname :"+stepName+ " detail : "+details);
		}else if(logStatus.equals(LogStatus.FAIL))
		{
			Log.fail("Stepname :"+stepName+ " detail : "+details);
		}else if(logStatus.equals(LogStatus.FATAL))
		{
			Log.fatal("Stepname :"+stepName+ " detail : "+details);
		}else if(logStatus.equals(LogStatus.WARNING))
		{
			Log.warn("Stepname :"+stepName+ " detail : "+details);
		}
		
	}
	
	
	public void log(LogStatus logStatus,String stepName,Throwable t )
	{
		extentReporter.log(logStatus, stepName, t);
		if(logStatus.equals(LogStatus.INFO) || logStatus.equals(LogStatus.PASS))
		{
		   Log.info(stepName);
		   Log.info(t);
		   t.printStackTrace();
		}else if(logStatus.equals(LogStatus.FAIL))
		{
			Log.fail(stepName);
			Log.fail(t);
			t.printStackTrace();
		}else if(logStatus.equals(LogStatus.FATAL))
		{
			Log.fatal(stepName);
			Log.fatal(t);
			t.printStackTrace();

		}else if(logStatus.equals(LogStatus.WARNING))
		{
			Log.warn(stepName);
			Log.warn(t);
			t.printStackTrace();
		}
	}
	
	public String addScreenCapture(String takeScreenShot) {
		// TODO Auto-generated method stub
		
		return extentReporter.addScreenCapture(takeScreenShot);
	}
}

**Comment by anshooarora** [comment]
I have seen these errors when you upgrade the version..

Can you do a clean build and try again?

**Comment by jawlitkp** [comment]
i did clean and build ,its still giving me same error

**Comment by anshooarora** [comment]
See [here](http://stackoverflow.com/questions/35186/how-do-i-fix-a-nosuchmethoderror) and [here](http://stackoverflow.com/questions/3695340/java-nosuchmethoderror).  Its just a build/compile issue due to the new version.

**Comment by jawlitkp** [comment]
it wasn't build issue ,i had extentmerge.jar in my lib folder which has old version of extent report jar which was causing issue

**Comment by anshooarora** [comment]
I see..  thanks for letting me know.
