### ISSUE TITLE
Cannot view the Report dashboard since no html file is created in the file path specified

### ISSUE THREAD

**Issue by HansinieJ** [anshooarora/extentreports#307]
public class AbstractTest {
 public static AppiumDriver<WebElement> driver;
 protected static ExtentReports report;
 protected ExtentTest logger;
 

	
	@BeforeTest
	public void setUp() throws Exception {

		
		AppiumDriverSetup.LoadResources();
		
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, AppiumDriverSetup.DeviceName());
		cap.setCapability(MobileCapabilityType.APP_PACKAGE, AppiumDriverSetup.AppPackage());
		cap.setCapability(MobileCapabilityType.APP_ACTIVITY, AppiumDriverSetup.AppActivity());
		cap.setCapability(MobileCapabilityType.APP, System.getProperty("user.dir") + AppiumDriverSetup.apkFile());
		cap.setCapability("newCommandTimeout",300);
		cap.setCapability(MobileCapabilityType.TAKES_SCREENSHOT, "true");
		driver = new AndroidDriver<WebElement>(new URL(AppiumDriverSetup.androidDriverURL()), cap);
		
page resource overriding.
		PathStore.LoadResources();
		  Date date= new Date();
		  
		 report = new ExtentReports("C:\\Users\\hansiniej\\workspace\\InvoiceHybridPOM\\Reports\\ResultDashboard.html",false);
		 
		  
		  WebDriverWait wait;
		  wait = new WebDriverWait(driver,120);
		  
		  System.out.println(new Timestamp(new Date().getTime()) + ": Waiting for web view");
		  wait.until(ExpectedConditions.visibilityOf(driver.findElementByClassName("android.webkit.WebView")));
		  System.out.println(new Timestamp(new Date().getTime()) + ": Wait ended");
		  
		  System.out.println(new Timestamp(new Date().getTime()) + ": Searching contexts");
		  
		  java.util.Set<String> contextNames = driver.getContextHandles();
		  for (String contextName : contextNames) {
			  System.out.println("Context Found: [" + contextName + "]");
		    if (contextName.contains("WEBVIEW")){
		    	System.out.println(new Timestamp(date.getTime()) + ": Switching context - " + contextName);
		    	driver.context(contextName);
		    	System.out.println(new Timestamp(date.getTime()) + ": Switched to web context - " + contextName);
		    	break;
		    }
		  }

		  try {
			  System.out.println(new Timestamp(date.getTime()) + ": Starting thread sleep");
			  Thread.sleep(10000);
		} catch (InterruptedException e) {
			
			e.printStackTrace();
		}

		  System.out.println(new Timestamp(new Date().getTime()) + ": Waiting for log in area to be visible");
		  wait.until(ExpectedConditions.visibilityOf(driver.findElementById("login-page")));
		  System.out.println(new Timestamp(new Date().getTime()) + ": Login logo is visible");
		  System.out.println(new Timestamp(new Date().getTime()) + ": Waiting for username textbox");

		  wait.until(ExpectedConditions.visibilityOf(driver.findElementByName("login")));
		  System.out.println(new Timestamp(new Date().getTime()) + ": Login textbox found");
		
	}
	
	@AfterMethod
	public void tearDown(ITestResult result) throws Exception {
		if (result.getStatus() == ITestResult.FAILURE)
		{
			
			String screenshot_path = Utilities.CaptureScreenshot(result.getName());
			String image = logger.addScreenCapture(screenshot_path);
			//String video = logger.addScreencast("");
			logger.log(LogStatus.FAIL,"Snapshot below:", image);
			//logger.log(LogStatus.FAIL,"Screencast below:", video);
		}
		logger.log(LogStatus.PASS, "Successful");
		report.endTest(logger);
		
		

	}
	@AfterTest
	public void TestClassEnd(ITestResult result) throws Exception {
		report.flush();
		driver.get(".\\Reports\\ResultDashboard.html");
		
	}
	
}

This is the test class which inherit form Abstract class.

public class LoginTest extends AbstractTest{

	
	@Test(dataProvider = "FetchData", dataProviderClass = core.TestNGDataProvider.class)
	public void testSuccessfulLogin(String urlname, String cciname, String user, String pass) throws IOException {

		logger = report.startTest("InvoiceTouch");
		logger.log(LogStatus.PASS,"Step details");
		
		LoginPageFlow pageFlow = new LoginPageFlow(this.driver);
		InvoicePageFlow invoicePageflow = pageFlow.LogIn(urlname, cciname, user, pass);
		invoicePageflow.verifyTitle();
		
	}
	
	
	@Test(dataProvider = "FetchData", dataProviderClass = core.TestNGDataProvider.class)
	public void RejectInvoice(String urlname, String cciname, String user, String pass) throws IOException {
		
		logger = report.startTest("InvoiceTouch");
		
		LoginPageFlow pageFlow = new LoginPageFlow(this.driver);
		InvoicePageFlow invoiceListFlow = pageFlow.LogIn(urlname, cciname, user, pass);
		System.out.println("Starting SelectInvoice Test");
		InvoiceActionPageFlow newInvoiceAction = invoiceListFlow.SelectInvoice();
		
		newInvoiceAction.verifyActionsButton();
		
		InvoiceApprovalPromptPageFlow prompt =  newInvoiceAction.selectRejectInvoice();
		
		
		System.out.println("Pick reject");
		prompt.verifyPromptTitle();
		System.out.println("verified title");
		
		prompt.verifyYesDisabled();
		prompt.typeReason();
		prompt.verifyYesEnabled();
		prompt.verifyRejectSuccess();
		System.out.println("success");
				
		
		
	}
	
}

This is the result of the TestNG console

FAILED CONFIGURATION: @AfterTest TestClassEnd
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.afterRun(TestRunner.java:1027)
	at org.testng.TestRunner.run(TestRunner.java:627)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

PASSED: RejectInvoice("invoiceapproval-test.compello.com", "cctest", "auth1", "auth1")
SKIPPED: testSuccessfulLogin
java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:992)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1082)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(Unknown Source)
	at core.TestNGDataProvider.getLoginData(TestNGDataProvider.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 20 more

===============================================
    Default test
    Tests run: 2, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 2, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@6d9c638: 62 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@2401f4c3: 30 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@5d22bbb7: 17 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@3d012ddd: 235 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 7 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@1175e2db: 6 ms

I used page object model for my test and used Extentreports version 2.05 from maven repository. Could you please you figured out what i have been missed in my code?

**Comment by testphreak** [comment]
Refer the documentation as the first point of reference. Specifically the TestNG [example](http://extentreports.relevantcodes.com/java/version2/docs.html#testng-example). I didn't see the close() method being called anywhere in your code. Close the stream before accessing the report. Call close() only once.

**Comment by anshooarora** [comment]
Closing issue as there was no response.
