### ISSUE TITLE
FreeMarker Template error

### ISSUE THREAD

**Issue by carlc986** [anshooarora/extentreports#310]
I recently added the ExtentReports JARs and java classes to a new project and when I run the suite, I get the following errors, would you know what is causing this? I am using IntelliJ, Selenium 2.49.1, and TestNG 6.9.9. Thanks for all your help! Carl

Jan 29, 2016 7:43:10 AM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> report.systemInfoMap[info]  [in template "Extent.ftl" at line 187, column 51]

----
Tip: It's the final [] step that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${report.systemInfoMap[info]}  [in template "Extent.ftl" at line 187, column 49]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
	at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:240)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at freemarker.template.Template.process(Template.java:325)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:171)
	at com.relevantcodes.extentreports.Report.flush(Report.java:440)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:668)
	at com.ux.framework.extentreports.ExtentReporterNG.generateReport(ExtentReporterNG.java:57)
	at org.testng.TestNG.generateReports(TestNG.java:1106)
	at org.testng.TestNG.run(TestNG.java:1065)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by carlc986** [comment]
One other note, which I'm sure is not the problem, but I imported the TestNG iReporter class as the one in the extentReports Jar gave unimplemented method errors.

**Comment by carlc986** [comment]
Looking further at the trace, it may be related to the iReporter, as the report is failing in:
at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:668)

and that was one of the unimplemented methods I got an error on when importing the iReporter from the extent reports JAR. What do you think?

**Comment by carlc986** [comment]
I figured it out, one of the System Env parameters I passed in was null and it failed the entire report, will close this.

**Comment by anshooarora** [comment]
Which null parameter was being passed, and to what method?  This may be a bug.

**Comment by carlc986** [comment]
// Add System Info to Report...
Map sysInfo = new HashMap();
sysInfo.put("Environment", System.getProperty("environment.reader")); // this was NULL
extent.addSystemInfo(sysInfo);

**Comment by anshooarora** [comment]
I was able to reproduce. Passing null throws this error. It shouldn't just crash like this, its a bug.

**Comment by anshooarora** [comment]
Fixed in 2.40.2-beta1.

**Comment by carlc986** [comment]
thx

**Comment by shineech** [comment]
@anshooarora i have the same problem when used the freemarker 2.3.26, could you show me how to fix this bug?
