### ISSUE TITLE
java.lang.NoClassDefFoundError: freemarker/template/Configuration

### ISSUE THREAD

**Issue by afaucogney** [anshooarora/extentreports#334]
I try to run extentreports for a couple of hours, but I failed:

Here is the error I get:
```
java.lang.NoClassDefFoundError: freemarker/template/Configuration
at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:75)
at com.relevantcodes.extentreports.Report.attach(Report.java:301)
at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:78)
at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:407)
at fr.x.app.y.Suites.System.LogSupportUser.getReport(LogSupportUser.java:37)
at fr.x.app.y.Suites.System.LogSupportUser.after(LogSupportUser.java:99)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

Here is my Gradle 

```
...
androidTestCompile 'com.relevantcodes:extentreports:2.40.+'
androidTestCompile 'org.freemarker:freemarker:2.3.23'
...
```

Here is the TestCase

```
import android.support.test.rule.ActivityTestRule;
import android.support.test.runner.AndroidJUnit4;
import android.test.suitebuilder.annotation.LargeTest;
import android.util.Log;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import fr.x.app.y.Activity.SplashScreenActivity;
import fr.x.app.y.Steps.AtomicTestSteps;
import hugo.weaving.DebugLog;

/**
 * Created by anthonyfaucogney on 15/02/2016.
 */

@RunWith(AndroidJUnit4.class)
@LargeTest
public class LogSupportUser {

    private static ExtentReports testReport;
    private static ExtentTest testCase;
    private static int testStepNumber = 0;

    @DebugLog
    private static ExtentReports getReport() {
        if (testReport == null)
            testReport = new ExtentReports("LogSupportUser.html");//, false);
        return testReport;
    }

    @DebugLog
    private static ExtentTest getTestCase() {
        if (testCase == null)
            testCase = getReport().startTest("LogSupportUser Test Case", "dfsqfdsf");
        return testCase;
    }

    @DebugLog
    private static void logTestStepReport(String description) {
        getTestCase().log(LogStatus.INFO, "Step " + testStepNumber, description);
        testStepNumber++;
    }

    @Rule
    public ActivityTestRule<SplashScreenActivity> mActivityRule = new ActivityTestRule(SplashScreenActivity.class);

    @DebugLog
    @Before
    public void before()  {
        Log.v("PROUT", "before");
        getTestCase();
    }

    @DebugLog
    @Before
    public void init() {
        Log.v("PROUT", "init");
        logTestStepReport("init");

        AtomicTestSteps.checkSplashScreen(getTestCase());
    }

    @DebugLog
    @Test
    public void goPreferences() {
        Log.v("PROUT", "Pref");
        logTestStepReport("goPreferences");

        AtomicTestSteps.checkHomeScreen(getTestCase());
        AtomicTestSteps.setPreferenceScreen(getTestCase());
    }

    @DebugLog
    @Test
    public void connectAsSupport() {
        Log.v("PROUT", "support");
        logTestStepReport("connectAsSupport");

        AtomicTestSteps.checkUnconnectOrDisconnect(getTestCase());
        AtomicTestSteps.connectSupportUser(getTestCase());
    }


    @DebugLog
    @After
    public void after() throws Exception {
        Log.v("PROUT", "after");
        // write all resources to report file
        getReport().endTest(getTestCase());
        getReport().flush();
    }
}
```

**Comment by anshooarora** [comment]
Do you have freemarker jar added to your project?

**Comment by anshooarora** [comment]
Can you check if you have multiple versions of freemarker associated with project, or multiple versions of freemarker.template.Configuration in your classpath?

**Comment by afaucogney** [comment]
I put nothing special about extentReport on ClassPath
I Just add what I quoted on Gradle file, I mean

androidTestCompile 'org.freemarker:freemarker:2.3.23'
androidTestCompile 'com.relevantcodes:extentreports:2.40.+'

Do I even need freemarker ? this is not a extentreport dependency ?

**Comment by afaucogney** [comment]
What do you mean exactly 

> by multiple versions of freemarker.template.Configuration in your classpath?

**Comment by anshooarora** [comment]
Freemarker is a dependency.  So are jsoup and xerial-sqlite.  Same issue if you have all dependencies added?

**Comment by ZhaoMuqiang** [comment]
Is the problem solved?
I also have the same problem.

**Comment by srinivaspullabhotla** [comment]
I have the similar problem. Don't know how to resolve it. Any thoughts on this please ?

Picked up _JAVA_OPTIONS: -Xmx2048M
[RemoteTestNG] detected TestNG version 6.9.6
[TestNG] Running:
  C:\Users\huntikm\AppData\Local\Temp\testng-eclipse-1203378038\testng-customsuite.xml

FAILED CONFIGURATION: @BeforeTest startTest
java.lang.NoSuchFieldError: VERSION_2_3_23
	at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:76)
	at com.relevantcodes.extentreports.Report.attach(Report.java:318)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:86)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:375)
	at com.webroot.automation.WiprepUtils.startTest(WiprepUtils.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:647)
	at org.testng.TestRunner.run(TestRunner.java:615)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

SKIPPED CONFIGURATION: @BeforeClass initializeValues
SKIPPED CONFIGURATION: @BeforeMethod reportHeader
SKIPPED CONFIGURATION: @AfterMethod getResult
SKIPPED CONFIGURATION: @AfterTest endReport
SKIPPED: mapTest

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 4
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 5
===============================================

[TestNG] Time taken by org.testng.reporters.EmailableReporter2@2e222612: 10 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@3315d2d7: 56 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 18 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@1f97cf0d: 11 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@13b13b5d: 91 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@49dc7102: 9 ms
