### ISSUE TITLE
creating ExtentReports instance throw exception

### ISSUE THREAD

**Issue by Fadih** [anshooarora/extentreports#419]
im using your sample for testNg

when  i trying to create new instance by
if (extent == null) {
            extent = new ExtentReports(filePath, true);

and i got this exception 

java.lang.NoSuchFieldError: VERSION_2_3_23
	at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:75)
	at com.relevantcodes.extentreports.Report.attach(Report.java:302)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:78)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:362)
	at extentFadi.ex.ExtentManager.Instance(ExtentManager.java:20)

**Comment by Fadih** [comment]
i found the problem it's not working with freemarker 2.3.21

**Comment by anshooarora** [comment]
Here is the [pom.xml](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/pom.xml).  2.3.23 is the required Freemarker version and it will not work with 2.3.21.

**Comment by rahul9892** [comment]
HI Anshoo,


Yes freemarker 2.3.23 has solved my problem, thanks for the great help.
