### ISSUE TITLE
I'm running selenium scripts using reflection concept. getting below extentreport error for all the scripts except last one. I found same thread [getting below exception while running report #213] but link to it is throwing 'Page not found' exception

### ISSUE THREAD

**Issue by gopal2602** [anshooarora/extentreports#437]
com.relevantcodes.extentreports.ExtentTestInterruptedException: Close was called before test could end safely using EndTest.
at com.relevantcodes.extentreports.Report.terminate(Report.java:416)
at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:708)
at driver.DriverScript.endScript(DriverScript.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:336)
at org.testng.SuiteRunner.run(SuiteRunner.java:268)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.run(TestNG.java:1064)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)

**Comment by anshooarora** [comment]
Are you calling close multiple times?  It should only be called once at the very end.  Please check docs.

**Comment by gopal2602** [comment]
Hi anshooarora,

Thanks for your reply. But I have used close (for extentreport object) only once in @AfterSuite annotation under DriverScript.java. Please find the attached "DriverScript.java" and the "ReportWriter_LogWriter.java". Hope you will do the needful...

[DriverScript - Copy.java.txt](https://github.com/anshooarora/extentreports/files/229158/DriverScript.-.Copy.java.txt)
[ReportWriter_LogWriter.java.txt](https://github.com/anshooarora/extentreports/files/229159/ReportWriter_LogWriter.java.txt)

**Comment by anshooarora** [comment]
Can you use `@BeforeMethod` and `@AfterMethod` to start and end tests.  The current usage does not seem right and looks error prone.  

See for example the last step in your script:

```
AReport.endTest(test);
```

You are ending step even for scenarios where no test was started.

**Comment by joseph873** [comment]
Am facing same issue ... any help

**Comment by anand853** [comment]
still im facing the same issue. how to report each end test ?

**Comment by sudheertreddy** [comment]
I am facing the same issue. @anshooarora  can you please help?

**Comment by joseph873** [comment]
in test suite , use below code 

	
	@AfterTest
    protected void afterSuite() {
		super.getReport().endTest(super.getLogger());
		super.getReport().flush();
		//super.getReport().close();
		//super.getDriver().quit();
    }

**Comment by sudheertreddy** [comment]
@AfterMethod
	public void getResult(ITestResult result){
		if(result.getStatus()==ITestResult.FAILURE){
			test.log(LogStatus.FAIL, "Test case failed is " + result.getName());
			test.log(LogStatus.FAIL, "Test case failed is " + result.getThrowable());
		}else if(result.getStatus()== ITestResult.SKIP){
			test.log(LogStatus.SKIP, "Test case skipped is "+ result.getName());	
		}
		extent.endTest(test);
		extent.flush();
		
	}

	@AfterTest
	public void endReport(){		
		extent.close();		
	}


This is my code. It doesn't work for me. Any other help is appreciated. I am blocked here
