### ISSUE TITLE
ExtentReport does not show whole error message for AssertJ condition

### ISSUE THREAD

**Issue by mikiwys** [anshooarora/extentreports#454]
Hi,

I am using in my project:
```
		<dependency>
			<groupId>com.vimalselvam</groupId>
			<artifactId>cucumber-extentsreport</artifactId>
			<version>1.0.0</version>
		</dependency>
```

In cucumber step definition I put _Assertj_ condition. _ExtentReport_ does not show whole error message.

Feature file:

```
Feature: Sample
  Scenario: Test
    Given create
```

Step definition:

```
@Given("^create")
public void create() throws Throwable {
  assertThat("not empty string").is(new Condition<String>(String::isEmpty, "empty"));
}
```

Error in console:

```
java.lang.AssertionError: 
Expecting:
 <"not empty string">
to be <empty>
	at com.package.StepDefinitions.create(StepDefinitions.java:38)
	at ✽.Given create(Sample.feature:3)
```

Details visible in ExtentReports:

```
java.lang.AssertionError: Expecting: <"not empty string"> to be at com.package.StepDefinitions.create(StepDefinitions.java:38) at ✽.Given create(Sample.feature:3)
```

The text `<empty>` is missing above.

**Comment by anshooarora** [comment]
@mikiwys - I would suggest opening this issue in Vimal's repo here:  https://github.com/email2vimalraj/CucumberExtentReporter.
