### ISSUE TITLE
Throws NullPointerException when running from Ant using maven

### ISSUE THREAD

**Issue by gitissuepost** [anshooarora/extentreports#470]
Hello Anshoo,

I am a beginner to ExtentReport. While executing my test project, I got NullPointerException while initializing the ExtentReports object.

I am using Maven and Ant in my project. While executing the project from Ant, I am getting this exception, but while executing the source file directly, I am not getting any exception.
[ExtentReportTest.zip](https://github.com/anshooarora/extentreports/files/257877/ExtentReportTest.zip)

OutPut :
[Ant Script Result.txt](https://github.com/anshooarora/extentreports/files/257880/Ant.Script.Result.txt)

Thanks.

**Comment by anshooarora** [comment]
Are you loading a config file?  If yes, does the file exist?

**Comment by gitissuepost** [comment]
No, I am not loading the config file. I hope, if I don't load the config, it will take the default one that is there with the Jar.

Also, I have added my project source code for your reference.

**Comment by vaibhavst** [comment]
Hi gitissuepost / anshooarora , 
I am newbie to ExtentReports, I am constantly getting following error when I try to execute the sample java code for ExtentReports

Exception in thread "main" java.lang.NullPointerException
	at com.relevantcodes.extentreports.Report.<init>(Report.java:606)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:72)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:418)
	at com.test.ETREports.main(ETREports.java:14)
My code sample is here 

public class ETREports {
    public static ExtentReports extent;
    public static void main(String[] args) {
        extent = new ExtentReports("C:\\SampleReports\\Report.html");  //This is line number 14 where I get error

I am using extentreports-java-2.41.0.jar , am missing something basic here ?

Thanks
Vaibhav

**Comment by anshooarora** [comment]
@gitissuepost - can you add the extent-reports jar from the website along with all dependencies or via pom.xml and try again?

@vaibhavst  - Do you have all the dependencies added?

**Comment by gitissuepost** [comment]
@anshooarora - It's running fine when I am running the code directly. But when I am running from Ant build.xml, it's throwing error. In both the case, I am using Maven
