### ISSUE TITLE
Exception OutOfMemoryError Java heap space

### ISSUE THREAD

**Issue by unleashurgeek** [anshooarora/extentreports#497]
Have a test suite of ~700 tests, I get a java heap space error when running ExtentReports close.

```
java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Arrays.java:2367)
at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
at java.lang.StringBuffer.append(StringBuffer.java:237)
at java.io.StringWriter.write(StringWriter.java:101)
at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
at freemarker.core.Environment.visit(Environment.java:324)
at freemarker.core.MixedContent.accept(MixedContent.java:54)
at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)

at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
at freemarker.core.Environment.visit(Environment.java:324)
at freemarker.core.MixedContent.accept(MixedContent.java:54)
at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)

at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
at freemarker.core.Environment.visit(Environment.java:324)
at freemarker.core.Macro$Context.runMacro(Macro.java:184)
at freemarker.core.Environment.invoke(Environment.java:701)
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
at freemarker.core.Environment.visit(Environment.java:324)
at freemarker.core.MixedContent.accept(MixedContent.java:54)
at freemarker.core.Environment.visitByHiddingParent(Environment.java:345
```

**Comment by anshooarora** [comment]
The stack-trace shows freemarker throwing this error.  Can you increase your heap space and test again?  http://stackoverflow.com/questions/1596009/java-lang-outofmemoryerror-java-heap-space

**Comment by unleashurgeek** [comment]
I performed some more testing since I got that stack (Also for reference when that stack is generated I have the max heap set to 1 GB), and it seems that it is more or less a "genuine" memory issue.

When each test completes I have it attaching an image of the resultant site to the report via base64. After the report finishes I flush the report. Yesterday I monitored the tests with VisualVM and noticed that after each flush the test is written to the report, but the memory is not cleared of the test. Thus over time the memory is getting filled with all the old tests. Furthermore, the more tests that were ran the longer it took to flush since it seemed it writes all the tests to the report after every flush.

To me this seems this is more of an enhancement/issue that needs to be resolved. Ideally when flushed it should output to the report and append it to the file, then clear that test from memory. Instead it is currently storing all tests in memory and each flush rewriting the entire report file.

**Comment by anshooarora** [comment]
Thanks for your findings.  This was the actual behavior in version 1 where tests were appended to the file, but was changed as a lot of calculations are done each time `flush()` executes and it requires all tests to be in memory for those calculations be done correctly.  

The template file can't be appended piece by piece, it builds the entire file from the template at once.  Moreover, appending would result in a ton of string replacements which is a painful process to manage.  I am open to working towards increasing the performance but I don't think appending to the file in multiple places is the right approach - it adds too much dependency on string markers and complicates the file build.  

I am open to suggestions and will mark this under research and will update you soon.

**Comment by anshooarora** [comment]
This is also one of those scenarios which would be better suited to be logged to database and report viewed via ExtentX.  A static HTML file with so many tests would turn the entire process slower.  The feature to only log to ExtentX is still under development though, with no ETA yet.

**Comment by anshooarora** [comment]
This feature will be part of version 3 (java8 only).  The static file will become very huge and all these issues are certain to popup so will allow logging only to the database instead of using a static file.

**Comment by rab2215** [comment]
I am experiencing this issue as well with a large set of tests, but in combination with a TestNG listener.  This issue is one that I have come across before with a custom html report and ended up modifying the listener to generate an html report for each test class instead of the entire test suite.  This was definitely an undesirable workaround, so I'm hopeful this can be resolved so I won't have to do it again.
