### ISSUE TITLE
java.lang.NoClassDefFoundError: freemarker/ext/beans/BeansWrapperBuilder

### ISSUE THREAD

**Issue by arpithaMaruthi** [anshooarora/extentreports#499]
HI Anshoo, 

Getting the following NoClassDefFoundError for Freemarker. BeansWrapperBuilder class in not found in the Freemarker jar.

below is the exception,

Exception in thread "main" java.lang.NoClassDefFoundError: freemarker/ext/beans/BeansWrapperBuilder
	at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:76)
	at com.relevantcodes.extentreports.Report.attach(Report.java:314)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:84)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:373)
	at framework.TasyReportingListener.generateReport(TasyReportingListener.java:26)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at framework.TasyAutomationRunner.main(TasyAutomationRunner.java:62)
Caused by: java.lang.ClassNotFoundException: freemarker.ext.beans.BeansWrapperBuilder
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more

Please help to resolve this.

**Comment by anshooarora** [comment]
Please make sure the freemarker dependency is added as in [pom.xml](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/pom.xml).  This will resolve the above error.

**Comment by arpithaMaruthi** [comment]
hi Anshoo, 

We are not using the dependency management tool in project because of some dependesices to be solved. We will do it in the later stages.

But i downloaded the freemarker jar from the Maven repository- freemarker-2.3.20 and coundn't find the class which BeansWrapperBuilder in the jar which is used in HTMLReporter class.
![jardownload](https://cloud.githubusercontent.com/assets/16558009/15812995/ce6bfade-2bd8-11e6-9383-dc00a4739d69.PNG)
![capture](https://cloud.githubusercontent.com/assets/16558009/15813004/e7e98b16-2bd8-11e6-9ea5-0f8bf96eb27b.PNG)

**Comment by anshooarora** [comment]
You need to use this version:

```
<dependency>
  <groupId>org.freemarker</groupId>
  <artifactId>freemarker</artifactId>
  <version>2.3.23</version>
</dependency>
```
