### ISSUE TITLE
Getting error - java.lang.NoClassDefFoundError: com/mongodb/MongoClientOptions

### ISSUE THREAD

**Issue by jitendra121** [anshooarora/extentreports#532]
Hi ,
    I have downloaded the extentreports  from https://github.com/anshooarora/extentreports
On CMD prompt Went  to extentreports-master\extentreports-master\java\extentreports
and RUN: mvn clean install -DskipTests
Now I added the extentreports-2.41.0.jar to my project and tried to run the test , but getting below error -

java.lang.NoClassDefFoundError: com/mongodb/MongoClientOptions
	at java.lang.Class.getDeclaredMethods0(Native Method)

	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getDeclaredMethod(Unknown Source)
	at java.io.ObjectStreamClass.getPrivateMethod(Unknown Source)
	at java.io.ObjectStreamClass.access$1700(Unknown Source)
	at java.io.ObjectStreamClass$2.run(Unknown Source)
	at java.io.ObjectStreamClass$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(Unknown Source)
	at java.io.ObjectStreamClass.lookup(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at java.util.HashMap.internalWriteEntries(Unknown Source)
	at java.util.HashMap.writeObject(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at sun.rmi.server.UnicastRef.marshalValue(Unknown Source)
	at sun.rmi.server.UnicastRef.invoke(Unknown Source)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(Unknown Source)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(Unknown Source)
	at com.sun.proxy.$Proxy1.invokeAdapter(Unknown Source)
	at com.arcot.test.adapter.RemoteRequestSender.invokeAdapter(RemoteRequestSender.java:58)
	at com.arcot.test.framework.TestScenarioRunner.callAdapter(TestScenarioRunner.java:623)
	at com.arcot.test.framework.TestScenarioRunner.runTestScenario(TestScenarioRunner.java:332)
	at com.arcot.test.framework.TestTypeRunner.runAllTestScenarios(TestTypeRunner.java:464)
	at com.arcot.test.framework.Gift.run(Gift.java:505)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.mongodb.MongoClientOptions
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 34 more

**Comment by anshooarora** [comment]
Are the dependencies being loaded as well?  MongoDB java driver is one of them.

```
    <dependencies>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.8.3</version>
        </dependency>
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.8.11.1</version>
        </dependency>
        <!-- <dependency>
            <groupId>hsqldb</groupId>
            <artifactId>hsqldb</artifactId>
            <version>1.8.0.10</version>
        </dependency> -->
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.23</version>
        </dependency>
        <dependency>
	        <groupId>org.mongodb</groupId>
	        <artifactId>mongodb-driver</artifactId>
	        <version>3.0.4</version>
	    </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.9.9</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```
