### ISSUE TITLE
NullPointerException on flush()

### ISSUE THREAD

**Issue by goldeelox** [anshooarora/extentreports#67]
Hi..great work on this project!
I'm getting NPEs when I call flush if the file path does not already exist. Looks like you just need a condition in the ReportInstance.initialize method to check for and create the directory structure if it doesn't already exist.

v2.04

```
java.io.FileNotFoundException: .\target\a\ExtentReports.html (The system cannot find the path specified)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at com.relevantcodes.extentreports.support.Writer.write(Writer.java:23)
	at com.relevantcodes.extentreports.ReportInstance.writeAllResources(ReportInstance.java:174)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:147)
	at ProjTest.afterSuite(ProjTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

**Comment by vishwathma** [comment]
Anshoo,

Please let me know the importance of flush(). Reports work when extent.flush() is removed with only extent.close() retained.

**Comment by anshooarora** [comment]
This issue will be fixed in the upcoming version.

Close and Flush do almost the same thing - except:

- If you fail to end any of your tests safely (by calling endTest), Close will still show them in the report with a warning sign.  Flush will not show them
- Close does not write SystemInfo to the report (Flush does)
- You can call Flush any number of times for a report session but Close only once, because:
- Close closes the stream so no other Extent commands can be used

**Comment by vishwathma** [comment]
For better performance of the reports, should both flush() & close() be retained in the code? Why the flush() & close() are separate? Can't they be combined into a single method? It's just my thought.

**Comment by anshooarora** [comment]
Vishi, that's because even though both do some of the same things, they have completely different purpose.  I will soon post a code sample to demonstrate this.  You can read a little about close here:

http://extentreports.relevantcodes.com/2x/docs.html#close-extent

**Comment by sthatip** [comment]
I am getting this error with v3.0.6. I am having to create the initial empty file and that is a problem with 'mvn clean package' goal.

**Comment by fviktor92** [comment]
I'm getting this error with 3.0.7. Report generation was working fine and then suddenly stopped working .
```
java.io.FileNotFoundException: \test-output\Bigscenario-20171116\report.html (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at com.aventstack.extentreports.utils.Writer.write(Writer.java:22)
	at com.aventstack.extentreports.reporter.ExtentHtmlReporter.flush(ExtentHtmlReporter.java:151)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.aventstack.extentreports.Report.notifyReporters(Report.java:247)
	at com.aventstack.extentreports.Report.flush(Report.java:169)
	at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:272)
	at utility.report.Report.getResult(Report.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:723)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```
