### ISSUE TITLE
Showing Error with extentreports.Logger.log

### ISSUE THREAD

**Issue by PKopargaonkar** [anshooarora/extentreports#73]
Hi Anshoo,

I am not able to generate reports showing follwing error

java.lang.NullPointerException
	at com.relevantcodes.extentreports.support.RegexMatcher.getNthMatch(RegexMatcher.java:37)
	at com.relevantcodes.extentreports.Logger.log(Logger.java:69)
	at com.relevantcodes.extentreports.AbstractLog.log(AbstractLog.java:72)
	at com.relevantcodes.extentreports.AbstractLog.log(AbstractLog.java:81)
	at com.relevantcodes.extentreports.ExtentReports.log(ExtentReports.java:67)
	at LoginTL.Login(LoginTL.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Please suggest ..

I have used extentreports-java-v2.05, extentreports-java-v2.04, extentreports-java-1.41 And 1.2a also but still its not resolved

**Comment by anshooarora** [comment]
What version are you using?  Did you check the docs?

Usage for version 1 and 2 is different.

**Comment by anshooarora** [comment]
Closing issue as there is no update.
